# Generated by Django 5.0.6 on 2024-05-21 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoBilling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_job', models.CharField(max_length=1000)),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('operational_model', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('store_id', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=255)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='autoBilling.operation')),
            ],
        ),
    ]
