# Generated by Django 5.0.6 on 2024-05-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoBilling', '0002_jobs_persona_product_delete_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
