# Generated by Django 5.0.6 on 2024-05-22 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoBilling', '0002_operation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='autoBilling.persona'),
        ),
        migrations.AddField(
            model_name='operation',
            name='preduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='autoBilling.product'),
        ),
    ]
