# Generated by Django 5.0.6 on 2024-05-22 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoBilling', '0003_operation_persona_operation_preduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='preduct',
            new_name='product',
        ),
    ]
