# Generated by Django 5.0.6 on 2024-05-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoBilling', '0003_query_delete_jobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
