# Generated by Django 5.0.6 on 2024-05-19 05:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoBilling', '0004_delete_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id_jwt', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('from_datetime', models.DateTimeField()),
                ('to_datetime', models.DateTimeField()),
                ('operational_model', models.CharField(max_length=255)),
                ('store_id', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='autoBilling.task')),
            ],
        ),
    ]
