# Generated by Django 5.0.6 on 2024-05-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoBilling', '0005_task_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('address_two', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
